<?xml version="1.0" encoding="UTF-8"?>
<!-- 声明内部DTD -->
<!DOCTYPE books [
	<!ELEMENT books (book*) >
	<!ELEMENT book (name,author,price)>
	<!ATTLIST book id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
]>
<books>
	<book id="01">
		<name>java从入门到精通</name>
		<author>Tom</author>
		<price>45.6</price>
	</book>
	<book id="02">
		<name>mysql学习指南</name>
		<author>lili</author>
		<price>49.6</price>
	</book>
</books>